update with openshift-drupal-kickstart 'last version' (7940959da4963aa799af2960a942b104c9b0e660 2014 Jul 23)

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -6,36 +6,51 @@
 
 set -e
 
+#
+# The PHP dir most be controlled by Drupal content
+#
+if [ -e "${OPENSHIFT_REPO_DIR}php" -a ! -h "${OPENSHIFT_REPO_DIR}php" ]
+then
+  echo "ERROR: The 'php' directory in your Git repo prevents Drupal from being installed.  Please remove 'php' and push again."
+  exit 5
+fi
+
 DRUPAL_DIR=${OPENSHIFT_DATA_DIR}drupal
 DRUPAL_SITE_DIR=${OPENSHIFT_DATA_DIR}sites
 
 echo
+
+# Drush settings
+cat >$OPENSHIFT_HOMEDIR/.drush/drushrc.php <<EOF
+<?php
+  \$options['uri'] = \$_ENV['OPENSHIFT_APP_DNS'];
+  \$options['root'] = \$_ENV['OPENSHIFT_REPO_DIR'].'php';
+EOF
 
 #
 # If there is no current download of Drupal, create one.
 #
 if [ ! -d "${OPENSHIFT_DATA_DIR}downloads/current" ]
 then
-  mkdir -p ${OPENSHIFT_DATA_DIR}bin
-  export DRUSH_SCRIPT=`find $OPENSHIFT_HOMEDIR -type f -name drush 2>/dev/null | head -1`
-  ln -s $DRUSH_SCRIPT ${OPENSHIFT_DATA_DIR}bin/drush
   mkdir -p ${OPENSHIFT_TMP_DIR}drupal
 
-  # Add Drush to the .bash_profile, which you must manually source in the shell
-  echo "PATH=\${OPENSHIFT_DATA_DIR}bin:\$PATH" >> ${OPENSHIFT_DATA_DIR}.bash_profile
-  echo "Run '. \${OPENSHIFT_DATA_DIR}.bash_profile' to load Drush into your SSH shell."
+  echo "Download and install the latest stable version of Drupal"
   echo
 
-  echo "Download and install the latest stable version of Drupal Commerce Kickstart"
-  echo
-
-  if ! $DRUSH_SCRIPT dl commerce_kickstart --destination=${OPENSHIFT_DATA_DIR}downloads --yes
+  mkdir -p ${OPENSHIFT_DATA_DIR}downloads
+  if ! drush dl commerce_kickstart --destination=${OPENSHIFT_DATA_DIR}downloads --yes
   then
     echo "ERROR: Unable download and install Drupal Commerce Kickstart."
     exit 7
   fi
-  export DRUPAL_INSTALL_DIR="${OPENSHIFT_DATA_DIR}downloads/`ls -1rt ${OPENSHIFT_DATA_DIR}downloads | head -1`"
-  ln -s ${DRUPAL_INSTALL_DIR} ${OPENSHIFT_DATA_DIR}downloads/current
+
+  #
+  # Link the /current symlink to the latest Drupal instance
+  #
+  rm -f ${OPENSHIFT_DATA_DIR}downloads/current
+  LATEST=$(ls -1t ${OPENSHIFT_DATA_DIR}downloads | head -1)
+  export DRUPAL_INSTALL_DIR="${OPENSHIFT_DATA_DIR}downloads/${LATEST}"
+  ln -s ${LATEST} ${OPENSHIFT_DATA_DIR}downloads/current
 
   mv $DRUPAL_INSTALL_DIR/sites $DRUPAL_INSTALL_DIR/sites.original
 
@@ -44,10 +59,11 @@ then
   #
   cp ${OPENSHIFT_REPO_DIR}.openshift/health_check.php ${DRUPAL_INSTALL_DIR}
 
+  patch ${DRUPAL_INSTALL_DIR}/.htaccess < ${OPENSHIFT_REPO_DIR}.openshift/.htaccess.patch
 
   echo "Drupal Commerce Kickstart installed to $DRUPAL_INSTALL_DIR"
 else
-  DRUPAL_INSTALL_DIR=`readlink -f ${OPENSHIFT_DATA_DIR}downloads/current`
+  DRUPAL_INSTALL_DIR=$(readlink -f ${OPENSHIFT_DATA_DIR}downloads/current)
   echo "Drupal Commerce Kickstart is already installed at $DRUPAL_INSTALL_DIR"
 fi
 
@@ -56,23 +72,20 @@ echo
 #
 # Link the /sites directory (where Drupal stores modules and files)
 # into the install dir in order to keep it easily accessible.
-#
+#/
 if [ ! -d "$DRUPAL_SITE_DIR" ]
 then
   cp -r $DRUPAL_INSTALL_DIR/sites.original $DRUPAL_SITE_DIR
-  ln -s $DRUPAL_SITE_DIR $DRUPAL_INSTALL_DIR/sites
+  ln -sfn ../../sites $DRUPAL_INSTALL_DIR/sites
 fi
 
-
 #
-# OpenShift looks for PHP files inside of app-root/runtime/repo/php
-# This runs on every build to ensure that the link is present (since
-# repo is recreated)
+# Ensure that the app-root/runtime/repo/php PHP directory points
+# to a valid Drupal instance directory
 #
+ln -sfn ../../data/downloads/current ${OPENSHIFT_REPO_DIR}php
 if [ ! -d "${OPENSHIFT_REPO_DIR}php" ]
-then
-  echo "Create link for $DRUPAL_INSTALL_DIR at ${OPENSHIFT_REPO_DIR}php"
-  ln -s $DRUPAL_INSTALL_DIR ${OPENSHIFT_REPO_DIR}php
-else
-  echo "Drupal Commerce Kickstart is already linked at ${OPENSHIFT_REPO_DIR}php"
+then  
+  echo "ERROR: Unable to link the PHP directory, as the current Drupal instance is not a valid directory."
+  exit 8
 fi
